[NOMERGE] refactor in separate files
digitronik/miqbox pull request #20
Opened 2019-08-15 17:11 UTC by digitronik

2019-08-22 18:51 UTC, digitronik commented
@Yadnyawalkya @valaparthvi @ganeshhubale 
please review... first go with oral and then local checks :+1:

2019-08-23 06:16 UTC, valaparthvi requested changes
Great refactor!

2019-08-23 06:16 UTC, valaparthvi commented on AUTHORS.md
> +- [Parthvi Vala](https://github.com/valaparthvi)
:smiley:

2019-08-23 06:16 UTC, valaparthvi commented on miqbox/config.yaml
> +    - master
Can you also add `ivanchuk`?

2019-08-23 06:16 UTC, valaparthvi commented on miqbox/images.py
> +    def with_image(cls, image):
OPTIONAL - I think renaming this to something like `instantiate` would make more sense. Again, we use `instantiate` a lot in integration_tests, which is why I think so, what do you think?

2019-08-23 06:16 UTC, valaparthvi commented on miqbox/config.yaml
> +    - master
Can you also add this file to `.gitignore`?
Making changes to this file causes it to show up in git diff.

2019-08-23 06:16 UTC, valaparthvi commented on miqbox/images.py
> +def images(local, remote, filter):
Earlier when I would do `miqbox images` it would list all the local images without asking for stream or version, which was nice, now it is kind of annoying when I am asked for stream and version every time I want that list.

Here's my idea - 
`miqbox images` - list all the images available locally
`miqbox images -r` - ask for stream, version and list images available remotely
`miqbox images --filter` - ask for stream, version and list all images available locally

This idea definitely can be improved. Or maybe add another flag `miqbox images --all` which would list all the local images.

Also, this can be enhanced to get remote images of a specific version, but maybe I'll work on that.

What do you think?

2019-08-25 09:29 UTC, digitronik commented on miqbox/images.py
> +def images(local, remote, filter):
restored: now
`miqbox images` : return all available local images
`miqbox --local or --remote`: return by asking `stream` and `version`

2019-08-25 09:34 UTC, digitronik commented on miqbox/config.yaml
> +    - master
No... our config its part of package so it should show changes in `git diff`.

2019-08-27 15:55 UTC, valaparthvi approved these changes
Thank you for bringing `miqbox images` back! :D

2019-08-27 16:55 UTC, digitronik commented
Lets merge this... we will add patches after this release :+1:

2019-08-27 16:55 UTC, merged